Repository Fund-Find/Fund-Find, pull requests merged in 2024-12, with the labels that each got.

#23 투자성향분석, ETF 종목 출력
  frontapp/src/App.jsx
  frontapp/src/assets/css/etfInfo.css
  frontapp/src/assets/css/result.css
  frontapp/src/assets/css/survey.css
  frontapp/src/pages/Result.jsx
  frontapp/src/pages/Survey.jsx
  frontapp/src/pages/etfInfo.jsx
  src/main/resources/application-secret.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: bug, enhancement

#33 Feature/30 mbti 유저매핑
  frontapp/src/App.jsx
  frontapp/src/assets/css/profile.css
  frontapp/src/components/Nav.jsx
  frontapp/src/components/PrivateRoute.jsx
  frontapp/src/pages/Login.jsx
  frontapp/src/pages/Main.jsx
  frontapp/src/pages/QuizshowList.jsx
  frontapp/src/pages/Survey.jsx
  frontapp/src/pages/profile.jsx
  src/main/java/com/example/domain/fund/controller/ApiV1ETFController.java
  src/main/java/com/example/domain/propensity/controller/ApiV1PropensityController.java
  src/main/java/com/example/domain/propensity/entity/Propensity.java
  src/main/java/com/example/domain/propensity/service/PropensityService.java
  src/main/java/com/example/domain/protect/ProtectedController.java
  src/main/java/com/example/domain/user/controller/UserController.java
  src/main/java/com/example/domain/user/dto/response/UserResponse.java
  src/main/java/com/example/domain/user/entity/SiteUser.java
  src/main/java/com/example/domain/user/service/UserService.java
  src/main/java/com/example/global/Jwt/JwtProvider.java
  src/main/java/com/example/global/config/WebMvcConfig.java
  src/main/java/com/example/global/security/ApiSecurityConfig.java
  src/main/java/com/example/global/security/JwtAuthorizationFilter.java
  src/main/java/com/example/global/security/SecurityConfig.java
  uploads/e3625012-6ec1-4811-a526-48d34764481e______2024-09-19_151752.png
Labels: feature

#36 Feature/27
  frontapp/.vite/deps/_metadata.json
  frontapp/src/App.jsx
  frontapp/src/main.jsx
  frontapp/src/pages/QuizshowList.jsx
  src/main/java/com/example/domain/quizShow/constant/QuizShowImage.java
  src/main/java/com/example/domain/quizShow/controller/ApiV1QuizShowController.java
  src/main/java/com/example/domain/quizShow/entity/Quiz.java
  src/main/java/com/example/domain/quizShow/entity/QuizShow.java
  src/main/java/com/example/domain/quizShow/entity/QuizShowCategoryEnum.java
  src/main/java/com/example/domain/quizShow/entity/QuizTypeEnum.java
  src/main/java/com/example/domain/quizShow/repository/QuizCategoryRepository.java
  src/main/java/com/example/domain/quizShow/repository/QuizRepository.java
  src/main/java/com/example/domain/quizShow/repository/QuizShowCategoryRepository.java
  src/main/java/com/example/domain/quizShow/repository/QuizShowRepository.java
  src/main/java/com/example/domain/quizShow/repository/QuizTypeRepository.java
  src/main/java/com/example/domain/quizShow/request/QuizRequest.java
  src/main/java/com/example/domain/quizShow/request/QuizShowCreateRequest.java
  src/main/java/com/example/domain/quizShow/request/QuizShowModifyRequest.java
  src/main/java/com/example/domain/quizShow/service/QuizCategoryService.java
  src/main/java/com/example/domain/quizShow/service/QuizShowService.java
  src/main/java/com/example/domain/quizShow/validator/QuizValidator.java
  src/main/java/com/example/global/initData/Init.java
  src/main/java/com/example/global/security/ApiSecurityConfig.java
  src/main/java/com/example/global/security/JwtAuthorizationFilter.java
  src/main/java/com/example/global/security/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/static/img/quizShow/Cryptocurrency.jpg
  src/main/resources/static/img/quizShow/Insurance.webp
  src/main/resources/static/img/quizShow/Investment.jpg
  src/main/resources/static/img/quizShow/RealEstate.webp
  src/main/resources/static/img/quizShow/Savings.jpg
  src/main/resources/static/img/quizShow/StockMarket.jpg
Labels: feature

#44 Feature/35
  frontapp/package-lock.json
  frontapp/package.json
  frontapp/src/App.jsx
  frontapp/src/assets/css/Nav.css
  frontapp/src/assets/css/pre/Pretendard-Black.otf
  frontapp/src/assets/css/pre/Pretendard-Bold.otf
  frontapp/src/assets/css/pre/Pretendard-ExtraBold.otf
  frontapp/src/assets/css/pre/Pretendard-ExtraLight.otf
  frontapp/src/assets/css/pre/Pretendard-Light.otf
  frontapp/src/assets/css/pre/Pretendard-Medium.otf
  frontapp/src/assets/css/pre/Pretendard-Regular.otf
  frontapp/src/assets/css/pre/Pretendard-SemiBold.otf
  frontapp/src/assets/css/pre/Pretendard-Thin.otf
  frontapp/src/assets/css/pre/alternative/Pretendard-Black.ttf
  frontapp/src/assets/css/pre/alternative/Pretendard-Bold.ttf
  frontapp/src/assets/css/pre/alternative/Pretendard-ExtraBold.ttf
  frontapp/src/assets/css/pre/alternative/Pretendard-ExtraLight.ttf
  frontapp/src/assets/css/pre/alternative/Pretendard-Light.ttf
  frontapp/src/assets/css/pre/alternative/Pretendard-Medium.ttf
  frontapp/src/assets/css/pre/alternative/Pretendard-Regular.ttf
  frontapp/src/assets/css/pre/alternative/Pretendard-SemiBold.ttf
  frontapp/src/assets/css/pre/alternative/Pretendard-Thin.ttf
  frontapp/src/assets/css/survey.css
  frontapp/src/components/Nav.jsx
  frontapp/src/components/PrivateRoute.jsx
  frontapp/src/pages/Login.jsx
  frontapp/src/pages/profile.jsx
  src/main/java/com/example/domain/user/controller/UserController.java
  uploads/ac21cacc-4e63-421c-bf71-3fa5719fefb5______2024-10-01_110950.png
Labels: feature

#45 Feature/modify page2
  frontapp/src/App.jsx
  frontapp/src/assets/css/etfDetail.css
  frontapp/src/assets/css/etfList.css
  frontapp/src/assets/css/module/ETFDetail.module.css
  frontapp/src/assets/css/result.css
  frontapp/src/assets/css/survey.css
  frontapp/src/components/ETFDetail.jsx
  frontapp/src/components/Survey.jsx
  frontapp/src/pages/ETFList.jsx
  frontapp/src/pages/Result.jsx
  frontapp/src/pages/profile.jsx
  src/main/java/com/example/domain/fund/controller/ApiV1ETFController.java
  src/main/java/com/example/domain/fund/service/ETFService.java
  src/main/java/com/example/domain/user/controller/UserController.java
  uploads/e10c0a1e-93d7-4404-8fd3-9af9fc4690ca_6ee71090-b24e-4c95-adc4-6b4067e7b985.jpg
  uploads/e900703f-8fc3-4139-b026-177cf342c8a1_5b9b80d2-1534-4626-b45a-e387ba9244ed.jpg
Labels: enhancement, fix

#47 Feature/46
  build.gradle
  frontapp/public/images/fflogo.webp
  frontapp/src/App.jsx
  frontapp/src/assets/css/Nav.css
  frontapp/src/assets/css/PasswordChange.css
  frontapp/src/assets/css/PasswordReset.css
  frontapp/src/assets/css/findId.css
  frontapp/src/assets/css/profile.css
  frontapp/src/components/Nav.jsx
  frontapp/src/components/PrivateRoute.jsx
  frontapp/src/components/PsswordChange.jsx
  frontapp/src/pages/FindId.jsx
  frontapp/src/pages/Login.jsx
  frontapp/src/pages/PasswordReset.jsx
  frontapp/src/pages/Register.jsx
  frontapp/src/pages/profile.jsx
  src/main/java/com/example/domain/user/controller/UserController.java
  src/main/java/com/example/domain/user/dto/request/PasswordChangeRequest.java
  src/main/java/com/example/domain/user/dto/request/PasswordResetRequest.java
  src/main/java/com/example/domain/user/dto/request/UserEmailRequest.java
  src/main/java/com/example/domain/user/dto/request/UserRequest.java
  src/main/java/com/example/domain/user/entity/PasswordResetToken.java
  src/main/java/com/example/domain/user/repository/PasswordResetTokenRepository.java
  src/main/java/com/example/domain/user/repository/UserRepository.java
  src/main/java/com/example/domain/user/service/EmailService.java
  src/main/java/com/example/domain/user/service/UserService.java
  src/main/java/com/example/global/Jwt/JwtProvider.java
  src/main/resources/application-secret.yml
  src/main/resources/application.yml
  uploads/271475d6-24fe-4dc4-9952-870449c44440______2024-11-19_134951.png
  uploads/afd8e951-92de-4eb4-a6dc-369f2d1c1d50______2024-11-19_134951.png
Labels: feature

#48 Feature/37
  frontapp/package-lock.json
  frontapp/package.json
  frontapp/src/App.jsx
  frontapp/src/components/Modal.jsx
  frontapp/src/pages/QuizShowDetail.jsx
  frontapp/src/pages/QuizshowList.jsx
  src/main/java/com/example/domain/quizShow/controller/ApiV1QuizShowController.java
  src/main/java/com/example/domain/quizShow/dto/QuizDTO.java
  src/main/java/com/example/domain/quizShow/dto/QuizShowDTO.java
  src/main/java/com/example/domain/quizShow/entity/Quiz.java
  src/main/java/com/example/domain/quizShow/entity/QuizShow.java
  src/main/java/com/example/domain/quizShow/repository/QuizAnswerRepository.java
  src/main/java/com/example/domain/quizShow/repository/QuizRepository.java
  src/main/java/com/example/domain/quizShow/repository/QuizShowRepository.java
  src/main/java/com/example/domain/quizShow/request/QuizRequest.java
  src/main/java/com/example/domain/quizShow/request/QuizSubmitRequest.java
  src/main/java/com/example/domain/quizShow/response/QuizSubmitResponse.java
  src/main/java/com/example/domain/quizShow/service/QuizShowService.java
  src/main/java/com/example/domain/user/repository/UserQuizResultRepository.java
  src/main/java/com/example/domain/user/service/UserService.java
  src/main/java/com/example/global/initData/Init.java
  src/main/java/com/example/global/security/ApiSecurityConfig.java
  src/main/java/com/example/global/security/GlobalExceptionHandler.java
  src/main/java/com/example/global/security/JwtAuthorizationFilter.java
  src/main/resources/application.yml
Labels: feature

#52 Feature/main page
  frontapp/public/images/투자성향분석 배너.png
  frontapp/src/App.jsx
  frontapp/src/assets/css/etfDetail.css
  frontapp/src/assets/css/etfList.css
  frontapp/src/assets/css/main.css
  frontapp/src/components/ETFDetail.jsx
  frontapp/src/components/Survey.jsx
  frontapp/src/pages/ETFList.jsx
  frontapp/src/pages/Main.jsx
  src/main/java/com/example/domain/fund/service/ETFInitService.java
  uploads/18003b59-8233-4350-bc11-88983175ef07____.jpeg
  uploads/5af47c66-21c0-461f-b1b0-5846810db797_1b0de178-8a27-4506-8f34-066648a83671.jpg
  uploads/e900703f-8fc3-4139-b026-177cf342c8a1_5b9b80d2-1534-4626-b45a-e387ba9244ed.jpg
Labels: enhancement

#53 Feature/49
  frontapp/package-lock.json
  frontapp/public/images/quizShow/Cryptocurrency.jpg
  frontapp/public/images/quizShow/Investment.jpg
  frontapp/public/images/quizShow/Savings.jpg
  frontapp/public/images/quizShow/insurance.jpg
  frontapp/public/images/quizShow/real_estate.jpg
  frontapp/public/images/quizShow/stock_market.jpg
  frontapp/src/assets/css/QuizShowDetail.css
  frontapp/src/assets/css/QuizShowList.css
  frontapp/src/components/Nav.jsx
  frontapp/src/pages/QuizShowDetail.jsx
  frontapp/src/pages/QuizshowList.jsx
  src/main/java/com/example/domain/quizShow/controller/ApiV1QuizShowController.java
  src/main/java/com/example/domain/quizShow/dto/QuizShowDTO.java
  src/main/java/com/example/domain/quizShow/entity/QuizShow.java
  src/main/java/com/example/domain/quizShow/service/QuizShowService.java
Labels: feature

#56 Feature/50
  frontapp/src/assets/css/Nav.css
  frontapp/src/assets/css/PasswordReset.css
  frontapp/src/assets/css/etfList.css
  frontapp/src/assets/css/findId.css
  frontapp/src/assets/css/main.css
  frontapp/src/components/Nav.jsx
  frontapp/src/pages/Main.jsx
Labels: enhancement

#58 메인페이지 퀴즈 연동
  frontapp/src/assets/css/main.css
  frontapp/src/pages/Main.jsx
  frontapp/src/pages/QuizshowList.jsx
  uploads/33579a1f-8ca0-4a40-ae36-3258740b50a8_fflogo.jpg
  uploads/8ad293e8-e898-40a0-9cdb-d0440d5b1ed1____.jpg
Labels: fix

#62 Feature/final modify
  build.gradle
  frontapp/package-lock.json
  frontapp/package.json
  frontapp/src/components/Survey.jsx
  frontapp/src/pages/ETFList.jsx
  frontapp/src/pages/Result.jsx
  frontapp/vite-project/package.json
  frontapp/vite-project/vite.config.js
  src/main/java/com/example/domain/favorite/controller/ApiV1ETFFavoriteController.java
  src/main/java/com/example/domain/favorite/entity/ETFFavorite.java
  src/main/java/com/example/domain/favorite/repository/ETFFavoriteRepository.java
  src/main/java/com/example/domain/favorite/service/ETFFavoriteService.java
  src/main/java/com/example/domain/fund/controller/ApiV1ETFController.java
  src/main/java/com/example/domain/fund/entity/ETF.java
  src/main/java/com/example/domain/fund/etfDTO/ETFDTO.java
  src/main/java/com/example/domain/fund/model/ETFSubCategory.java
  src/main/java/com/example/domain/fund/repository/ETFRepository.java
  src/main/java/com/example/domain/fund/service/ETFInitService.java
  src/main/java/com/example/domain/fund/service/ETFService.java
  src/main/java/com/example/domain/propensity/service/PropensityService.java
  src/main/java/com/example/domain/user/controller/UserController.java
  src/main/java/com/example/domain/user/dto/UserDTO.java
  src/main/java/com/example/domain/user/entity/SiteUser.java
  src/main/java/com/example/domain/user/service/UserService.java
  uploads/0b1954b9-8df5-4831-99c6-9ad00d74437e____.gif
  uploads/2a9c5bbe-4faf-4c58-a8b1-14db6cd83bdb____.gif
  uploads/5fc56701-c963-4bf3-9ae1-19df8e984d0e____.gif
Labels: enhancement

#63 Feature/101
  frontapp/src/assets/css/Nav.css
  frontapp/src/assets/css/profile.css
  frontapp/src/pages/Login.jsx
  frontapp/src/pages/Main.jsx
  frontapp/src/pages/Register.jsx
  frontapp/src/pages/profile.jsx
  src/main/java/com/example/domain/fund/controller/ApiV1ETFController.java
  src/main/java/com/example/domain/user/controller/UserController.java
  src/main/java/com/example/domain/user/dto/request/UserRequest.java
  src/main/java/com/example/domain/user/service/UserService.java
  src/main/java/com/example/global/security/GlobalExceptionHandler.java
  uploads/ad1d3500-9f75-4d3d-bde6-40f5eea12bd2_____.gif
  uploads/df5c4fbb-15d4-435b-8154-b3176b7947f0_____.gif
  uploads/e3625012-6ec1-4811-a526-48d34764481e______2024-09-19_151752.png
Labels: fix

#65 Feature/55
  frontapp/package-lock.json
  frontapp/package.json
  frontapp/src/assets/css/QuizShowList.css
  frontapp/src/assets/css/quizshow.css
  frontapp/src/components/QuizShowCreateModal.jsx
  frontapp/src/pages/QuizShowDetail.jsx
  frontapp/src/pages/QuizshowList.jsx
  frontapp/src/types/index.js
  frontapp/vite.config.js
  src/main/java/com/example/domain/quizShow/controller/ApiV1QuizShowController.java
  src/main/java/com/example/domain/quizShow/dto/QuizShowCategoryDTO.java
  src/main/java/com/example/domain/quizShow/dto/QuizShowDTO.java
  src/main/java/com/example/domain/quizShow/entity/Quiz.java
  src/main/java/com/example/domain/quizShow/entity/QuizAnswer.java
  src/main/java/com/example/domain/quizShow/entity/QuizShow.java
  src/main/java/com/example/domain/quizShow/request/QuizShowCreateRequest.java
  src/main/java/com/example/domain/quizShow/request/QuizSubmitRequest.java
  src/main/java/com/example/domain/quizShow/response/QuizShowListResponse.java
  src/main/java/com/example/domain/quizShow/service/QuizShowService.java
  src/main/java/com/example/domain/user/entity/SiteUser.java
  src/main/java/com/example/global/initData/Init.java
  src/main/java/com/example/global/security/SecurityUser.java
Labels: feature
